task_planner:
    resource: "@TaskPlannerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@TaskPlannerBundle/Controller/'
    type: annotation

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"
   prefix: /

app_task:
    resource: "@TaskPlannerBundle/Controller/TaskController.php"
    type:     annotation

app_comments:
    resource: "@TaskPlannerBundle/Controller/CommentsController.php"
    type:     annotation

app_category:
    resource: "@TaskPlannerBundle/Controller/CategoryController.php"
    type:     annotation

app_category:
    resource: "@TaskPlannerBundle/Controller/CategoryController.php"
    type:     annotation

app_category:
    resource: "@TaskPlannerBundle/Controller/CategoryController.php"
    type:     annotation
